# -*- coding: utf-8 -*-
"""Greek Scripture Tokenization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMc01bASYrBpOlcJmkfmJA4NUv29xy-6
"""

!pip install cltk

import re
from cltk import NLP

# Step 1: Input the Greek text
# Replace this with the scripture text (below is John 19)
text = """
Τότε οὖν ἔλαβεν ὁ Πιλᾶτος τὸν Ἰησοῦν, καὶ ἐμαστίγωσεν.
2 Καὶ οἱ στρατιῶται πλέξαντες στέφανον ἐξ ἀκανθῶν ἐπέθηκαν αὐτοῦ τῇ κεφαλῇ, καὶ ἱμάτιον πορφυροῦν περιέβαλον αὐτόν.
3 Καὶ ἔλεγον, Χαῖρε, ὁ βασιλεὺς τῶν Ἰουδαίων· καὶ ἔδιδοσαν αὐτῷ ῥαπίσματα.
4 Ἐξῆλθεν οὖν πάλιν ὁ Πιλᾶτος ἔξω, καὶ λέγει αὐτοῖς, Ἴδε ἄγω ὑμῖν αὐτὸν ἔξω, ἵνα γνῶτε ὅτι οὐδεμίαν εὑρίσκω ἐν αὐτῷ αἰτίαν.
5 Ἐξῆλθεν οὖν ὁ Ἰησοῦς ἔξω, φορῶν τὸν στέφανον τῶν ἀκανθῶν καὶ τὸ πορφυροῦν ἱμάτιον. Καὶ λέγει αὐτοῖς, Ἴδε ὁ ἄνθρωπος.
6 Ὅτε οὖν εἶδον αὐτὸν οἱ ἀρχιερεῖς καὶ οἱ ὑπηρέται ἐκραύγασαν, λέγοντες, Σταύρωσον, σταύρωσον αὐτόν. Λέγει αὐτοῖς ὁ Πιλᾶτος, Λάβετε αὐτὸν ὑμεῖς καὶ σταυρώσατε· ἐγὼ γὰρ οὐχ εὑρίσκω ἐν αὐτῷ αἰτίαν.
7 Ἀπεκρίθησαν αὐτῷ οἱ Ἰουδαῖοι, Ἡμεῖς νόμον ἔχομεν, καὶ κατὰ τὸν νόμον ἡμῶν ὀφείλει ἀποθανεῖν, ὅτι ἑαυτὸν Υἱὸν τοῦ Θεοῦ ἐποίησεν.
8 Ὅτε οὖν ἤκουσεν ὁ Πιλᾶτος τοῦτον τὸν λόγον, μᾶλλον ἐφοβήθη.
9 Καὶ εἰσῆλθεν εἰς τὸ πραιτώριον πάλιν, καὶ λέγει τῷ Ἰησοῦ, Πόθεν εἶ σύ; Ὁ δὲ Ἰησοῦς ἀπόκρισιν οὐκ ἔδωκεν αὐτῷ.
10 Λέγει οὖν αὐτῷ ὁ Πιλᾶτος, Ἐμοὶ οὐ λαλεῖς; Οὐκ οἶδας ὅτι ἐξουσίαν ἔχω σταυρῶσαί σε, καὶ ἐξουσίαν ἔχω ἀπολῦσαί σε;
11 Ἀπεκρίθη Ἰησοῦς, Οὐκ εἶχες ἐξουσίαν οὐδεμίαν κατ’ ἐμοῦ, εἰ μὴ ἦν δεδομένον σοι ἄνωθεν· διὰ τοῦτο ὁ παραδούς με σοι μείζονα ἁμαρτίαν ἔχει.
12 Ἐκ τούτου ὁ Πιλᾶτος ἐζήτει ἀπολῦσαι αὐτόν· οἱ δὲ Ἰουδαῖοι ἔκραζον, λέγοντες, Ἐὰν τοῦτον ἀπολύσῃς, οὐκ εἶ φίλος τοῦ Καίσαρος· πᾶς ὁ βασιλέα ἑαυτὸν ποιῶν ἀντιλέγει τῷ Καίσαρι.
13 Ὁ Πιλᾶτος οὖν, ἀκούσας τῶν λόγων τούτων, ἤγαγεν ἔξω τὸν Ἰησοῦν, καὶ ἐκάθισεν ἐπὶ βήματος εἰς τόπον λεγόμενον Λιθόστρωτον, Ἑβραϊστὶ δὲ Γαββαθά.
14 ἦν δὲ παρασκευὴ τοῦ πάσχα, ὥρα ἦν ὡσεὶ ἕκτη. Καὶ λέγει τοῖς Ἰουδαίοις, Ἴδε ὁ βασιλεὺς ὑμῶν.
15 Ἐκραύγασαν οὖν ἐκεῖνοι, Ἆρον ἆρον, σταύρωσον αὐτόν. Λέγει αὐτοῖς ὁ Πιλᾶτος, Τὸν βασιλέα ὑμῶν σταυρώσω; Ἀπεκρίθησαν οἱ ἀρχιερεῖς, Οὐκ ἔχομεν βασιλέα εἰ μὴ Καίσαρα.
16 Τότε οὖν παρέδωκεν αὐτὸν αὐτοῖς ἵνα σταυρωθῇ. Παρέλαβον δὲ τὸν Ἰησοῦν.
17 Καὶ βαστάζων τὸν σταυρὸν ἐξῆλθεν εἰς τὸν λεγόμενον Κρανίου Τόπον, ὃ λέγεται Ἑβραϊστὶ Γολγοθά.
18 ὅπου αὐτὸν ἐσταύρωσαν, καὶ μετ’ αὐτοῦ ἄλλους δύο ἐντεῦθεν καὶ ἐντεῦθεν, μέσον δὲ τὸν Ἰησοῦν.
19 Ἔγραψεν δὲ καὶ τίτλον ὁ Πιλᾶτος καὶ ἔθηκεν ἐπὶ τοῦ σταυροῦ· ἦν δὲ γεγραμμένον, Ἰησοῦς ὁ Ναζωραῖος ὁ βασιλεὺς τῶν Ἰουδαίων.
20 Τοῦτον οὖν τὸν τίτλον πολλοὶ ἀνέγνωσαν τῶν Ἰουδαίων, ὅτι ἐγγὺς ἦν ὁ τόπος τῆς πόλεως ὅπου ἐσταυρώθη ὁ Ἰησοῦς· ἦν δὲ γεγραμμένον Ἑβραϊστί, Ῥωμαϊστί, Ἑλληνιστί.
21 Ἔλεγον οὖν τῷ Πιλᾶτῳ οἱ ἀρχιερεῖς τῶν Ἰουδαίων, Μὴ γράφε, Ὁ βασιλεὺς τῶν Ἰουδαίων, ἀλλ’ ὅτι ἐκεῖνος εἶπεν, Βασιλεύς εἰμι τῶν Ἰουδαίων.
22 Ἀπεκρίθη ὁ Πιλᾶτος, Ὃ γέγραφα γέγραφα.
23 Οἱ οὖν στρατιῶται, ὅτε ἐσταύρωσαν τὸν Ἰησοῦν, ἔλαβον τὰ ἱμάτια αὐτοῦ, καὶ ἐποίησαν τέσσαρα μέρη, ἑκάστῳ στρατιώτῃ μέρος, καὶ τὸν χιτῶνα. ἦν δὲ ὁ χιτὼν ἄραφος, ἐκ τῶν ἄνωθεν ὑφαντὸς δι’ ὅλου.
24 Εἶπον οὖν πρὸς ἀλλήλους, Μὴ σχίσωμεν αὐτόν, ἀλλὰ λάχωμεν περὶ αὐτοῦ τίνος ἔσται· ἵνα ἡ γραφὴ πληρωθῇ, λέγουσα, Διεμερίσαντο τὰ ἱμάτιά μου ἑαυτοῖς, καὶ ἐπὶ τὸν ἱματισμόν μου ἔβαλον κλῆρον. Οἱ μὲν οὖν στρατιῶται ταῦτα ἐποίησαν.25 Εἱστήκεισαν δὲ παρὰ τῷ σταυρῷ τοῦ Ἰησοῦ ἡ μήτηρ αὐτοῦ καὶ ἡ ἀδελφὴ τῆς μητρὸς αὐτοῦ, Μαρία ἡ τοῦ Κλωπᾶ, καὶ Μαρία ἡ Μαγδαληνή.
26 Ἰησοῦς οὖν ἰδὼν τὴν μητέρα καὶ τὸν μαθητὴν παρεστῶτα ὃν ἠγάπα, λέγει τῇ μητρί, Γύναι, Ἴδε ὁ υἱός σου.
27 Εἶτα λέγει τῷ μαθητῇ, Ἴδε ἡ μήτηρ σου. Καὶ ἀπ’ ἐκείνης τῆς ὥρας ἔλαβεν αὐτὴν ὁ μαθητὴς εἰς τὰ ἴδια.
28 Μετὰ τοῦτο εἰδὼς ὁ Ἰησοῦς ὅτι πάντα ἤδη τετέλεσται, ἵνα τελειωθῇ ἡ γραφή, λέγει, Διψῶ.
29 Σκεῦος ἔκειτο ὄξους μεστόν· σπόγγον οὖν μεστὸν τοῦ ὄξους ὑσσώπῳ περιθέντες προσήνεγκαν αὐτοῦ τῷ στόματι.
30 Ὅτε οὖν ἔλαβεν τὸ ὄξος ὁ Ἰησοῦς εἶπεν, Τετέλεσται· καὶ κλίνας τὴν κεφαλὴν παρέδωκεν τὸ πνεῦμα.
31 Οἱ οὖν Ἰουδαῖοι, ἐπεὶ παρασκευὴ ἦν, ἵνα μὴ μείνῃ ἐπὶ τοῦ σταυροῦ τὰ σώματα ἐν τῷ σαββάτῳ, ἦν γὰρ μεγάλη ἡ ἡμέρα ἐκείνου τοῦ σαββάτου, ἠρώτησαν τὸν Πιλᾶτον ἵνα κατεαγῶσιν αὐτῶν τὰ σκέλη καὶ ἀρθῶσιν.
32 Ἦλθον οὖν οἱ στρατιῶται, καὶ τοῦ μὲν πρώτου κατέαξαν τὰ σκέλη, καὶ τοῦ ἄλλου τοῦ συσταυρωθέντος αὐτῷ·
33 ἐπὶ δὲ τὸν Ἰησοῦν ἐλθόντες, ὡς εἶδον ἤδη αὐτὸν τεθνηκότα, οὐ κατέαξαν αὐτοῦ τὰ σκέλη,
34 ἀλλ’ εἷς τῶν στρατιωτῶν λόγχῃ αὐτοῦ τὴν πλευρὰν ἔνυξεν, καὶ εὐθὺς ἐξῆλθεν αἷμα καὶ ὕδωρ.
35 Καὶ ὁ ἑωρακὼς μεμαρτύρηκεν, καὶ ἀληθινὴ αὐτοῦ ἐστιν ἡ μαρτυρία· κἀκεῖνος οἶδεν ὅτι ἀληθῆ λέγει, ἵνα καὶ ὑμεῖς πιστεύσητε.
36 Ἐγένετο γὰρ ταῦτα ἵνα ἡ γραφὴ πληρωθῇ, Ὀστοῦν οὐ συντριβήσεται αὐτοῦ.
37 Καὶ πάλιν ἑτέρα γραφὴ λέγει, Ὄψονται εἰς ὃν ἐξεκέντησαν.
38 Μετὰ δὲ ταῦτα ἠρώτησεν τὸν Πιλᾶτον Ἰωσὴφ ὁ ἀπὸ Ἀριμαθαίας, ὢν μαθητὴς τοῦ Ἰησοῦ, κεκρυμμένος δὲ διὰ τὸν φόβον τῶν Ἰουδαίων, ἵνα ἄρῃ τὸ σῶμα τοῦ Ἰησοῦ· καὶ ἐπέτρεψεν ὁ Πιλᾶτος. Ἦλθεν οὖν καὶ ἦρεν τὸ σῶμα αὐτοῦ.
39 Ἦλθεν δὲ καὶ Νικόδημος, ὁ ἐλθὼν πρὸς αὐτὸν νυκτὸς τὸ πρῶτον, φέρων μῖγμα σμύρνης καὶ ἀλόης ὡς λίτρας ἑκατόν.
40 ἔλαβον οὖν τὸ σῶμα τοῦ Ἰησοῦ, καὶ ἔδησαν αὐτὸ ἐν ὀθονίοις μετὰ τῶν ἀρωμάτων, καθὼς ἔθος ἐστὶν τοῖς Ἰουδαίοις ἐνταφιάζειν.
41 Ἦν δὲ ἐν τῷ τόπῳ ὅπου ἐσταυρώθη κῆπος, καὶ ἐν τῷ κήπῳ μνημεῖον καινὸν ἐν ᾧ οὐδέπω οὐδεὶς ἦν τεθειμένος.
42 Ἐκεῖ οὖν διὰ τὴν παρασκευὴν τῶν Ἰουδαίων, ὅτι ἐγγὺς ἦν τὸ μνημεῖον, ἔθηκαν τὸν Ἰησοῦν.
"""

# Step 2: Preprocess the text (clean punctuation and standardize spaces)
def clean_text(text):
    import re
    text = re.sub(r"[.,;·]", "", text)  # Remove punctuation
    text = re.sub(r"\s+", " ", text).strip()  # Standardize spaces
    return text

text_cleaned = clean_text(text)
print("Cleaned Text:")
print(text_cleaned)

import re #regular expressions used to delineate verses

def split_into_verses(text):
    """
    Split the input text into a dictionary of verse numbers and their corresponding text.
    This function handles text where verses may or may not start on new lines.
    """
    verses = {}  # Dictionary to store verse numbers and text

    # Use a regex pattern to find verse numbers followed by space and text
    verse_pattern = re.compile(r"(\d+)\s([^0-9]+)")

    # Find all matches of the pattern
    matches = verse_pattern.finditer(text)

    for match in matches:
        verse_num = int(match.group(1))  # Extract verse number
        verse_text = match.group(2).strip()  # Extract verse text
        verses[verse_num] = verse_text  # Add to dictionary

    return verses

# Call the function and print results
verses = split_into_verses(text_cleaned)
print("Verses Dictionary:")
for verse_num, verse_text in verses.items():
    print(f"Verse {verse_num}: {verse_text}")

# Step 4: Tokenize non-lemmatized words and lemmatized words by verse
def tokenize_scripture(verses):
    """
    Tokenize scripture into non-lemmatized and lemmatized tokens for each verse.
    Includes print statements for debugging and progress tracking.
    """
    nlp = NLP(language="grc")  # Initialize CLTK for Greek
    non_lemmatized_tokens = {}
    lemmatized_tokens = {}

    for verse_num, verse_text in verses.items():
        print(f"Processing Verse {verse_num}: {verse_text}")  # Debug print for current verse

        # Non-lemmatized tokens (word forms as-is)
        non_lemmatized_tokens[verse_num] = verse_text.split()
        print(f"Non-Lemmatized Tokens: {non_lemmatized_tokens[verse_num]}")  # Debug print for non-lemmatized tokens

        # Lemmatized tokens (root forms)
        doc = nlp.analyze(verse_text)
        lemmatized_tokens[verse_num] = [word.lemma for word in doc.words]
        print(f"Lemmatized Tokens: {lemmatized_tokens[verse_num]}")  # Debug print for lemmatized tokens

    return non_lemmatized_tokens, lemmatized_tokens

# Step 5: Ensure CLTK models are available
try:
    non_lemmatized_tokens, lemmatized_tokens = tokenize_scripture(verses)
except Exception as e:
    print(f"Error during tokenization: {e}")

# Step 6: Display results
print("\nNon-Lemmatized Tokens by Verse:")
for verse, tokens in non_lemmatized_tokens.items():
    print(f"Verse {verse}: {tokens}")

print("\nLemmatized Tokens by Verse:")
for verse, tokens in lemmatized_tokens.items():
    print(f"Verse {verse}: {tokens}")